[book]
title = "Rust for RTL Verification"
authors = ["Fable 5 as Ray Salemi"]
language = "en"
description = "An introduction to Rust using pyuvm as a base"

[output.html]
additional-css = ["github-markdown.css"]


[output.pdf]
print-background = true
display-header-footer = true
footer-template = "<div style='font-size:9px; width:100%; text-align:center; color:#555;'><span class='pageNumber'></span> / <span class='totalPages'></span></div>"
header-template = "<span></span>"
margin-bottom = "0.7in"

