//! Component lifecycle and hierarchy traversal (design-doc §5.2/§5.3).
//!
//! build/connect are **constructor conventions**, not trait methods
//! (review-memo R3): a component's `new(config, ...)` constructs its
//! children (`// build:`) and takes channel endpoints as arguments
//! (`// connect:`). What remains at runtime is this trait.

use crate::objection::{ObjectionGuard, ObjectionRegistry};

/// Agent activity (pyuvm's ConfigDB `is_active` int becomes an enum —
/// mapping row 42; illegal values are unrepresentable).
#[derive(Copy, Clone, Debug, PartialEq, Eq)]
pub enum Active {
    Active,
    Passive,
}

/// Collector for `check`-phase failures (design-doc §5.3 signature).
#[derive(Default)]
pub struct CheckSink {
    errors: Vec<String>,
}

impl CheckSink {
    pub fn new() -> CheckSink {
        CheckSink::default()
    }
    pub fn error(&mut self, msg: impl Into<String>) {
        let msg = msg.into();
        rustdv_sim::log::error(&msg);
        self.errors.push(msg);
    }
    pub fn is_ok(&self) -> bool {
        self.errors.is_empty()
    }
    pub fn errors(&self) -> &[String] {
        &self.errors
    }
    pub fn into_result(self) -> Result<(), String> {
        if self.errors.is_empty() {
            Ok(())
        } else {
            Err(format!("{} check failure(s): {}", self.errors.len(), self.errors.join("; ")))
        }
    }
}

/// Handed to `start`: spawning and objections (design-doc §5.3).
pub struct RunCtx {
    objections: ObjectionRegistry,
}

impl RunCtx {
    #[allow(clippy::new_without_default)]
    pub fn new() -> RunCtx {
        RunCtx { objections: ObjectionRegistry::new() }
    }

    /// Port of raise_objection, returning a guard whose Drop is
    /// drop_objection (pyuvm: uvm_component.objection()).
    pub fn raise_objection(&self, description: &str) -> ObjectionGuard {
        self.objections.raise(description)
    }

    pub fn objections(&self) -> &ObjectionRegistry {
        &self.objections
    }

    /// Wait until every raised objection has been dropped. Logs the pyuvm
    /// "you never objected" warning if nothing was ever raised.
    pub async fn all_objections_dropped(&self) {
        self.objections.wait_all_dropped().await;
    }
}

/// The runtime lifecycle (design-doc §5.3). Default empty bodies replicate
/// pyuvm's no-op base methods — override only what you use.
pub trait Component {
    /// Spawn free-running behavior (drivers, monitors); bottom-up order,
    /// like pyuvm's run_phase spawning.
    fn start(&mut self, ctx: &mut RunCtx) {
        let _ = ctx;
    }
    /// Top-down, post-run.
    fn extract(&mut self) {}
    /// Top-down.
    fn check(&mut self, errors: &mut CheckSink) {
        let _ = errors;
    }
    /// Top-down.
    fn report(&self) {}
    fn final_phase(&self) {}
}

/// Structural traversal over the ownership tree (design-doc D5.2).
/// Generated by `#[derive(Component)]` for structs whose children are
/// fields marked `#[component(child)]`; hand-implementable by design
/// (OQ-15: the derive is convenience, not requirement).
pub trait ComponentNode: Component {
    /// The component's type-level name (hierarchical path is synthesized
    /// from field names during traversal).
    fn node_name(&self) -> &'static str;

    /// Visit direct children as (field_name, node) pairs.
    fn visit_children(&mut self, f: &mut dyn FnMut(&str, &mut dyn ComponentNode));
}

// ---------------------------------------------------------------------------
// Traversals (pyuvm _s09 orders: run is bottom-up, the rest top-down)
// ---------------------------------------------------------------------------

/// Bottom-up: children start before parents (pyuvm run_phase order).
pub fn start_all(node: &mut dyn ComponentNode, ctx: &mut RunCtx) {
    node.visit_children(&mut |_name, child| start_all(child, ctx));
    node.start(ctx);
}

/// Top-down.
pub fn extract_all(node: &mut dyn ComponentNode) {
    node.extract();
    node.visit_children(&mut |_name, child| extract_all(child));
}

/// Top-down.
pub fn check_all(node: &mut dyn ComponentNode, sink: &mut CheckSink) {
    node.check(sink);
    node.visit_children(&mut |_name, child| check_all(child, sink));
}

/// Top-down.
pub fn report_all(node: &mut dyn ComponentNode) {
    node.report();
    node.visit_children(&mut |_name, child| report_all(child));
}

pub fn final_all(node: &mut dyn ComponentNode) {
    node.final_phase();
    node.visit_children(&mut |_name, child| final_all(child));
}

/// The standard post-run tail: extract → check → report → final, returning
/// `Err` if any check failed (an `Err` fails the test, design-doc §0.6).
pub fn run_extract_check_report(node: &mut dyn ComponentNode) -> Result<(), String> {
    extract_all(node);
    let mut sink = CheckSink::new();
    check_all(node, &mut sink);
    report_all(node);
    final_all(node);
    sink.into_result()
}

/// Debug printer: the `visit_children` walker serving pyuvm's hierarchy
/// print (design-doc §5.2).
pub fn print_hierarchy(node: &mut dyn ComponentNode) {
    fn rec(node: &mut dyn ComponentNode, path: &str) {
        rustdv_sim::log::info(&format!("{path} ({})", node.node_name()));
        let parent = path.to_string();
        node.visit_children(&mut |name, child| {
            rec(child, &format!("{parent}.{name}"));
        });
    }
    rec(node, "top");
}
