//! # rustdv-uvm
//!
//! The UVM analog (design-doc §5, as revised by review-memo R1–R6):
//!
//! - Transactions are plain structs with std derives (R1) — no base trait.
//! - The component tree is the ownership tree (R2): children are struct
//!   fields; [`ComponentNode`] provides traversal, hand-implementable or
//!   generated by `#[derive(Component)]`.
//! - build/connect are constructor conventions (R3); the runtime lifecycle
//!   is the [`Component`] trait: start/extract/check/report/final.
//! - Configuration is typed config structs passed to constructors (R4).
//! - Variation points are constructor injection (R5) — no factory.
//! - Communication is channels + [`AnalysisPort`] + the sequencer
//!   handshake, preserved event-for-event from pyuvm (R6, §5.6).

pub mod analysis;
pub mod channel;
pub mod component;
pub mod fifo;
pub mod objection;
pub mod sequence;

pub use analysis::{AnalysisFifo, AnalysisPort, Subscriber};
pub use channel::{channel, Receiver, Sender, TlmEmpty, TlmError, TlmFull};
pub use component::{
    check_all, extract_all, final_all, report_all, run_extract_check_report, start_all, Active,
    CheckSink, Component, ComponentNode, RunCtx,
};
pub use fifo::TlmFifo;
pub use objection::{ObjectionGuard, ObjectionRegistry};
pub use sequence::{
    ResponseQueue, SeqCtx, SeqError, SeqItem, SeqItemPort, Sequence, Sequencer, TxnId,
};
